### ISSUE TITLE
Add save/load for the CNN

### ISSUE THREAD

**Issue by ArtLinkov** [NeuraLegion/shainet#63]
Admittedly, it took a while until we got some time on our hands to work on this... :)
We should have it done by the end of the week. For now, save/load to JSON will be supported.

**Comment by fab1an2** [comment]
Save yes but similar Marshal (from Ruby)
I woul like to export to C.

For example I learn in crystal, test in crystal and when finish create a C file with only one function. All weights, bias etc. are inside C. Only put input data and get output
int shainet(data *input, output...)
{

**Comment by bararchy** [comment]
@fab1an2 saying that here: https://github.com/NeuraLegion/crystal-fann/issues/11 was enough :) 
It's a crystal thing, not related to either crystal-fann or SHAInet

**Comment by bonopublico** [comment]
sound like uTensor, converter tensorflow to .cpp .h files for embeded in project C
Very interesting
